# Generated by Django 3.2.12 on 2023-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrequest', '0002_songrequest_weektostart'),
    ]

    operations = [
        migrations.CreateModel(
            name='weektostart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='songrequest',
            name='weektostart',
        ),
    ]
